const majorToNameMap = new Map();
const nameToMajorMap = new Map();

const add = function (major, name) {
    majorToNameMap.set(major, name);
    nameToMajorMap.set(name, major);
};

add(0, "None");
add(1, "LocalQuery");
add(3, "Job");
add(4, "Section");
add(5, "Page");
add(6, "ImageContainer");
add(7, "Content");
add(8, "User");
add(9, "Department");
add(10, "Telegram");
add(11, "Product");
add(12, "OrganizationalGroup");
add(13, "Organization");
add(14, "QueryTemplate");
add(15, "ArticleType");
add(16, "ArticleConfig");
add(17, "UserRole");
add(18, "ArchiveInfo");
add(19, "ArticlePartType");
add(20, "Assignment");
add(22, "Import_Image");
add(23, "Article");
add(24, "Image");
add(26, "Responsibility");
add(27, "Status");
add(28, "UserSessionInfo");
add(31, "NILayoutModel");
add(32, "OrganizationSetting");
add(33, "XmlElement");
add(35, "SubProduct");
add(36, "WorkflowTrigger");
add(37, "PublicationDate");
add(38, "ExportDestination");
add(39, "UserDataConfig");
add(40, "AdminLock");
add(41, "ExportPlugin");
add(43, "PageFormat");
add(44, "XmlElementExport");
add(46, "CharacterExport");
add(47, "SystemSetting");
add(48, "History");
add(49, "UserBylineImage");
add(50, "BylineType");
add(51, "SpecialChar");
add(52, "BylineExport");
add(53, "ProductSetting");
add(54, "ContentSchema");
add(55, "ReproHandler");
add(56, "Profile");
add(57, "TelegramSetting");
add(59, "ResourceStatus");
add(60, "ResourceSchedule");
add(61, "ResourceScheduleEvent");
add(62, "CalendarEvent");
add(63, "CalendarDate");
add(64, "ExportConfig");
add(65, "Project");
add(66, "ArticlePartConfig");
add(68, "Byline");
add(69, "ArticlePart");
add(70, "Ad");
add(71, "Privilege");
add(72, "PrivilegeGroup");
add(73, "File");
add(74, "Directory");
add(75, "TelegramUser");
add(76, "ImageLink");
add(77, "StoreLocation");
add(78, "ArticleVersion");
add(79, "EntityFlag");
add(90, "QueryTemplateShortcut");
add(91, "QueryTemplateControl");
add(92, "AdminPrivilege");
add(93, "ValueMap");
add(95, "ArticleVersionType");
add(97, "CalendarEventType");
add(98, "CalendarPeriod");
add(99, "Resource");
add(100, "LinguisticProposal");
add(101, "ExternalSystem");
add(102, "ArticleSystemLink");
add(103, "ImageSystemLink");
add(104, "ContentSystemLink");
add(105, "PageSystemLink");
add(106, "TelegramSystemLink");
add(107, "JobSystemLink");
add(108, "ProjectSystemLink");
add(109, "PageTemplate");
add(110, "ServiceWatch");
add(111, "ServiceWatchLink");
add(112, "PageLayoutTemplate");
add(113, "LayoutDocumentTemplate");
add(114, "SectionSystemLink");
add(116, "ModuleUsage");
add(117, "CMSSyncMapping");
add(118, "ContentLink");
add(120, "ContentContainer");
add(121, "UserSystemLink");
add(122, "PrintFlow");
add(123, "ServiceProvider");
add(124, "ServerPrintChannel");
add(125, "PrintChannelLink");
add(126, "ArticlePartSystemLink");
add(127, "ExternalSystemSetting");
add(128, "Contact");
add(129, "ContactAssociation");
add(130, "ContentContainerSystemLink");
add(131, "ImageContainerSystemLink");
add(132, "FileManagerItem");
add(133, "LibraryLayoutItem");
add(134, "JobLinkReference");
add(135, "ArticleLinkReference");
add(136, "Placement");
add(139, "Line");
add(140, "PublicationSetting");
add(141, "AdClass");
add(142, "AdHeader");
add(143, "LineProfile");
add(144, "Tag");
add(145, "XmlElementConfig");
add(146, "EntityLock");
add(147, "NewsMLVersion");
add(148, "EntityTemplate");
add(149, "IdmlTemplate");
add(150, "ExternalSystemLink");
add(152, "TrustedInformation");

const majorToName = function (major) {
    return majorToNameMap.get(major);
};

const nameToMajor = function (name) {
    return nameToMajorMap.get(name);
};

export {majorToName, nameToMajor}